CREATE TABLE projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event VARCHAR(255),
    external_id VARCHAR(255),
    job_type VARCHAR(255),
    street VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    county VARCHAR(255),
    postal_code VARCHAR(10),
    country VARCHAR(255),
    territory VARCHAR(255),
    latitude DECIMAL(10, 6),
    longitude DECIMAL(10, 6),
    downpayment DECIMAL(10, 2),
    discounts_total DECIMAL(10, 2),
    base_system_cost DECIMAL(10, 2),
    battery_total DECIMAL(10, 2),
    adders_total DECIMAL(10, 2),
    dealer_fee DECIMAL(10, 2),
    annual_usage INT,
    subhub_id INT,
    contract_amount DECIMAL(10, 2),
    utility_company VARCHAR(255),
    utility_bill DECIMAL(10, 2),
    module_name VARCHAR(255),
    module_manufacturer VARCHAR(255),
    module_watts INT,
    module_description TEXT,
    module_total_panels INT,
    inverter_name VARCHAR(255),
    inverter_manufacturer VARCHAR(255),
    inverter_quantity INT,
    battery_name VARCHAR(255),
    battery_manufacturer VARCHAR(255),
    battery_price DECIMAL(10, 2),
    battery_size_kwh DECIMAL(10, 2),
    battery_quantity INT,
    annual_production DECIMAL(10, 3),
    finance_type VARCHAR(255),
    contract_type VARCHAR(255),
    finance_partner VARCHAR(255),
    finance_term_year INT,
    finance_rate DECIMAL(5, 2),
    finance_escalator_rate DECIMAL(5, 2),
    finance_ppw DECIMAL(10, 2),
    finance_monthly_payment DECIMAL(10, 2),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(20),
    owner_email VARCHAR(255),
    proposal_url TEXT,
    contract_signed_url TEXT,
    system_size_kw DECIMAL(10, 2),
    system_size_w INT,
    sales_representative_name VARCHAR(255),
    sales_representative_email VARCHAR(255)
);
